version: 2
project_name: authcrunch

release:
  github:
    owner: greenpau
    name: caddy-security
  draft: false
  prerelease: auto
  footer: "{{ .Env.GO_AUTHCRUNCH_CHANGELOG }}"

checksum:
  name_template: "{{.ProjectName}}_{{.Version}}_SHA256SUMS"

builds:
  - id: authcrunch
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/authcrunch
    binary: ./bin/authcrunch
    flags:
      - -trimpath
      - -mod=readonly
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags: -s -w

  - id: caddy-authenticator
    main: ./cmd/caddy-authenticator
    binary: caddy-authenticator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -mod=readonly
    ldflags:
      - >-
        -s -w
        -X main.appVersion={{ .Version }}
        -X main.gitCommit={{ .Commit }}
        -X main.buildUser=goreleaser
        -X main.buildDate={{ .Date }}

archives:
  - id: authcrunch
    ids:
      - authcrunch
  - id: caddy-authenticator
    ids:
      - caddy-authenticator
    name_template: "caddy-authenticator_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - src: cmd/caddy-authenticator/README.md
        strip_parent: true

nfpms:
  - id: authcrunch
    ids:
      - authcrunch
    maintainer: "Paul Greenberg <greenpau@outlook.com>"
    file_name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs?:'
    - '^readme:'
    - '^tests?:'
    - '^misc:'
    - '^update'
    - '^github'
    - '^release'
    - '^chore:'
    - '^ops:'
    - 'signed the CLA'
    # - '^\w+\s+' # a hack to remove commit messages without colons thus don't correspond to a package
