project_name: authcrunch

release:
  github:
    owner: greenpau
    name: caddy-security
  draft: false
  prerelease: auto

checksum:
  name_template: "{{.ProjectName}}_{{.Version}}_SHA256SUMS"

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/authcrunch
    binary: ./bin/authcrunch
    flags:
      - -trimpath
      - -mod=readonly
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags: -s -w


nfpms:
  - id: authcrunch
    maintainer: "Paul Greenberg <greenpau@outlook.com>"
    file_name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs?:'
    - '^readme:'
    - '^tests?:'
    - '^misc:'
    - '^update'
    - '^github'
    - '^release'
    - '^chore:'
    - 'signed the CLA'
    # - '^\w+\s+' # a hack to remove commit messages without colons thus don't correspond to a package
